/*
 * register layouts (VRAM, GPUSTAT, draw mode) live in core/gpu_types.h and are
 * re-exported here so existing call sites keep resolving.
 *
 * D3D11/D3D12/Metal enum values preserved for numeric stability
 * but the corresponding backends are dropped.
 */

#ifndef CUPID_UTIL_GPU_TYPES_H
#define CUPID_UTIL_GPU_TYPES_H

#include "common/types.h"
#include "core/gpu_types.h"

typedef enum {
  GPU_RENDER_API_NONE = 0,
  GPU_RENDER_API_D3D11,        /* dropped */
  GPU_RENDER_API_D3D12,        /* dropped */
  GPU_RENDER_API_VULKAN,       /* deferred */
  GPU_RENDER_API_OPENGL,
  GPU_RENDER_API_OPENGL_ES,    /* deferred */
  GPU_RENDER_API_METAL,        /* dropped */
} gpu_render_api_t;

typedef enum {
  GPU_VSYNC_MODE_DISABLED = 0,
  GPU_VSYNC_MODE_FIFO,
  GPU_VSYNC_MODE_MAILBOX,
  GPU_VSYNC_MODE_COUNT,
} gpu_vsync_mode_t;

typedef enum {
  GPU_TEXTURE_FORMAT_UNKNOWN = 0,
  GPU_TEXTURE_FORMAT_RGBA8,
  GPU_TEXTURE_FORMAT_BGRA8,
  GPU_TEXTURE_FORMAT_RGB565,
  GPU_TEXTURE_FORMAT_RGB5A1,
  GPU_TEXTURE_FORMAT_A1BGR5,
  GPU_TEXTURE_FORMAT_R8,
  GPU_TEXTURE_FORMAT_D16,
  GPU_TEXTURE_FORMAT_D24S8,
  GPU_TEXTURE_FORMAT_D32F,
  GPU_TEXTURE_FORMAT_D32FS8,
  GPU_TEXTURE_FORMAT_R16,
  GPU_TEXTURE_FORMAT_R16I,
  GPU_TEXTURE_FORMAT_R16U,
  GPU_TEXTURE_FORMAT_R16F,
  GPU_TEXTURE_FORMAT_R32I,
  GPU_TEXTURE_FORMAT_R32U,
  GPU_TEXTURE_FORMAT_R32F,
  GPU_TEXTURE_FORMAT_RG8,
  GPU_TEXTURE_FORMAT_RG16,
  GPU_TEXTURE_FORMAT_RG16F,
  GPU_TEXTURE_FORMAT_RG32F,
  GPU_TEXTURE_FORMAT_RGBA16,
  GPU_TEXTURE_FORMAT_RGBA16F,
  GPU_TEXTURE_FORMAT_RGBA32F,
  GPU_TEXTURE_FORMAT_RGB10A2,
  GPU_TEXTURE_FORMAT_SRGBA8,
  GPU_TEXTURE_FORMAT_BC1,
  GPU_TEXTURE_FORMAT_BC2,
  GPU_TEXTURE_FORMAT_BC3,
  GPU_TEXTURE_FORMAT_BC7,
  /* Backward-compat alias for window_info_t::surface_format. */
  GPU_TEXTURE_FORMAT_RGBA5551 = GPU_TEXTURE_FORMAT_RGB5A1,
  GPU_TEXTURE_FORMAT_MAX_COUNT = GPU_TEXTURE_FORMAT_BC7 + 1,
} gpu_texture_format_t;

typedef enum {
  GPU_SHADER_STAGE_VERTEX = 0,
  GPU_SHADER_STAGE_FRAGMENT,
  GPU_SHADER_STAGE_GEOMETRY,
  GPU_SHADER_STAGE_COMPUTE,
  GPU_SHADER_STAGE_MAX_COUNT,
} gpu_shader_stage_t;

typedef enum {
  GPU_SHADER_LANGUAGE_NONE = 0,
  GPU_SHADER_LANGUAGE_HLSL,        /* deferred */
  GPU_SHADER_LANGUAGE_GLSL,
  GPU_SHADER_LANGUAGE_GLSL_ES,
  GPU_SHADER_LANGUAGE_GLSL_VK,     /* deferred */
  GPU_SHADER_LANGUAGE_MSL,         /* dropped */
  GPU_SHADER_LANGUAGE_SPV,         /* deferred */
  GPU_SHADER_LANGUAGE_COUNT,
} gpu_shader_language_t;

typedef enum {
  GPU_DRIVER_TYPE_MOBILE_FLAG   = 0x100,
  GPU_DRIVER_TYPE_SOFTWARE_FLAG = 0x200,

  GPU_DRIVER_TYPE_UNKNOWN              = 0,
  GPU_DRIVER_TYPE_AMD_PROPRIETARY      = 1,
  GPU_DRIVER_TYPE_AMD_MESA             = 2,
  GPU_DRIVER_TYPE_INTEL_PROPRIETARY    = 3,
  GPU_DRIVER_TYPE_INTEL_MESA           = 4,
  GPU_DRIVER_TYPE_NVIDIA_PROPRIETARY   = 5,
  GPU_DRIVER_TYPE_NVIDIA_MESA          = 6,
  GPU_DRIVER_TYPE_APPLE_PROPRIETARY    = 7,
  GPU_DRIVER_TYPE_APPLE_MESA           = 8,
  GPU_DRIVER_TYPE_DOZEN_MESA           = 9,

  GPU_DRIVER_TYPE_IMAGINATION_PROPRIETARY = 0x100 | 1,
  GPU_DRIVER_TYPE_IMAGINATION_MESA        = 0x100 | 2,
  GPU_DRIVER_TYPE_ARM_PROPRIETARY         = 0x100 | 3,
  GPU_DRIVER_TYPE_ARM_MESA                = 0x100 | 4,
  GPU_DRIVER_TYPE_QUALCOMM_PROPRIETARY    = 0x100 | 5,
  GPU_DRIVER_TYPE_QUALCOMM_MESA           = 0x100 | 6,
  GPU_DRIVER_TYPE_BROADCOM_PROPRIETARY    = 0x100 | 7,
  GPU_DRIVER_TYPE_BROADCOM_MESA           = 0x100 | 8,

  GPU_DRIVER_TYPE_LLVMPIPE   = 0x200 | 1,
  GPU_DRIVER_TYPE_SWIFTSHADER = 0x200 | 2,
  GPU_DRIVER_TYPE_WARP       = 0x200 | 3,
} gpu_driver_type_t;

typedef enum {
  GPU_PRESENT_RESULT_OK = 0,
  GPU_PRESENT_RESULT_SKIP_PRESENT,
  GPU_PRESENT_RESULT_EXCLUSIVE_FULLSCREEN_LOST,
  GPU_PRESENT_RESULT_DEVICE_LOST,
} gpu_present_result_t;

#endif /* CUPID_UTIL_GPU_TYPES_H */
