#ifndef CUPID_CORE_TYPES_H
#define CUPID_CORE_TYPES_H

#include "common/types.h"

#include <string.h>

/* PS1 physical/virtual addresses are both 32-bit. */
typedef u32 physical_memory_address_t;
typedef u32 virtual_memory_address_t;

/* CPU pipeline tick / global VM tick aliases. */
typedef s32 tick_count_t;
typedef u64 global_ticks_t;
typedef u64 game_hash_t;

typedef enum : u32 {
  MEMORY_ACCESS_TYPE_READ,
  MEMORY_ACCESS_TYPE_WRITE,
} memory_access_type_t;

typedef enum : u32 {
  MEMORY_ACCESS_SIZE_BYTE,
  MEMORY_ACCESS_SIZE_HALFWORD,
  MEMORY_ACCESS_SIZE_WORD,
} memory_access_size_t;

typedef enum : u8 {
  CONSOLE_REGION_AUTO,
  CONSOLE_REGION_NTSC_J,
  CONSOLE_REGION_NTSC_U,
  CONSOLE_REGION_PAL,
  CONSOLE_REGION_COUNT,
} console_region_t;

typedef enum : u8 {
  DISC_REGION_NTSC_J, /* SCEI */
  DISC_REGION_NTSC_U, /* SCEA */
  DISC_REGION_PAL,    /* SCEE */
  DISC_REGION_OTHER,
  DISC_REGION_NON_PS1,
  DISC_REGION_COUNT,
} disc_region_t;

typedef enum : u8 {
  CPU_EXECUTION_MODE_INTERPRETER,
  CPU_EXECUTION_MODE_CACHED_INTERPRETER,
  CPU_EXECUTION_MODE_RECOMPILER,
  CPU_EXECUTION_MODE_COUNT,
} cpu_execution_mode_t;

typedef enum : u8 {
  PGXP_MODE_DISABLED,
  PGXP_MODE_MEMORY,
  PGXP_MODE_CPU,
} pgxp_mode_t;

typedef enum : u8 {
  GPU_RENDERER_AUTOMATIC,
  GPU_RENDERER_SOFTWARE,
  GPU_RENDERER_HARDWARE_OPENGL,
  GPU_RENDERER_COUNT,
} gpu_renderer_t;

typedef enum : u8 {
  DISPLAY_DEINTERLACING_MODE_DISABLED,
  DISPLAY_DEINTERLACING_MODE_WEAVE,
  DISPLAY_DEINTERLACING_MODE_BLEND,
  DISPLAY_DEINTERLACING_MODE_ADAPTIVE,
  DISPLAY_DEINTERLACING_MODE_PROGRESSIVE,
  DISPLAY_DEINTERLACING_MODE_COUNT,
} display_deinterlacing_mode_t;

typedef enum : u8 {
  GPU_TEXTURE_FILTER_NEAREST,
  GPU_TEXTURE_FILTER_BILINEAR,
  GPU_TEXTURE_FILTER_BILINEAR_BIN_ALPHA,
  GPU_TEXTURE_FILTER_JINC2,
  GPU_TEXTURE_FILTER_JINC2_BIN_ALPHA,
  GPU_TEXTURE_FILTER_XBR,
  GPU_TEXTURE_FILTER_XBR_BIN_ALPHA,
  GPU_TEXTURE_FILTER_SCALE2X,
  GPU_TEXTURE_FILTER_SCALE3X,
  GPU_TEXTURE_FILTER_MMPX,
  GPU_TEXTURE_FILTER_MMPX_ENHANCED,
  GPU_TEXTURE_FILTER_MMPX_QUALITY,
  GPU_TEXTURE_FILTER_COUNT,
} gpu_texture_filter_t;

typedef enum : u8 {
  GPU_DITHERING_MODE_UNSCALED,
  GPU_DITHERING_MODE_UNSCALED_SHADER_BLEND,
  GPU_DITHERING_MODE_SCALED,
  GPU_DITHERING_MODE_SCALED_SHADER_BLEND,
  GPU_DITHERING_MODE_TRUE_COLOR,
  GPU_DITHERING_MODE_TRUE_COLOR_FULL,
  GPU_DITHERING_MODE_MAX_COUNT,
} gpu_dithering_mode_t;

typedef enum : u8 {
  GPU_DOWNSAMPLE_MODE_DISABLED,
  GPU_DOWNSAMPLE_MODE_BOX,
  GPU_DOWNSAMPLE_MODE_ADAPTIVE,
  GPU_DOWNSAMPLE_MODE_COUNT,
} gpu_downsample_mode_t;

typedef enum : u8 {
  GPU_WIREFRAME_MODE_DISABLED,
  GPU_WIREFRAME_MODE_OVERLAY_WIREFRAME,
  GPU_WIREFRAME_MODE_ONLY_WIREFRAME,
  GPU_WIREFRAME_MODE_COUNT,
} gpu_wireframe_mode_t;

typedef enum : u8 {
  GPU_LINE_DETECT_MODE_DISABLED,
  GPU_LINE_DETECT_MODE_QUADS,
  GPU_LINE_DETECT_MODE_BASIC_TRIANGLES,
  GPU_LINE_DETECT_MODE_AGGRESSIVE_TRIANGLES,
  GPU_LINE_DETECT_MODE_COUNT,
} gpu_line_detect_mode_t;

typedef enum : u8 {
  GPU_DUMP_COMPRESSION_MODE_DISABLED,
  GPU_DUMP_COMPRESSION_MODE_ZST_LOW,
  GPU_DUMP_COMPRESSION_MODE_ZST_DEFAULT,
  GPU_DUMP_COMPRESSION_MODE_ZST_HIGH,
  GPU_DUMP_COMPRESSION_MODE_XZ_LOW,
  GPU_DUMP_COMPRESSION_MODE_XZ_DEFAULT,
  GPU_DUMP_COMPRESSION_MODE_XZ_HIGH,
  GPU_DUMP_COMPRESSION_MODE_MAX_COUNT,
} gpu_dump_compression_mode_t;

typedef enum : u8 {
  DISPLAY_CROP_MODE_NONE,
  DISPLAY_CROP_MODE_OVERSCAN,
  DISPLAY_CROP_MODE_OVERSCAN_UNCORRECTED,
  DISPLAY_CROP_MODE_BORDERS,
  DISPLAY_CROP_MODE_BORDERS_UNCORRECTED,
  DISPLAY_CROP_MODE_MAX_COUNT,
} display_crop_mode_t;

typedef enum : u8 {
  DISPLAY_FINE_CROP_MODE_NONE,
  DISPLAY_FINE_CROP_MODE_VIDEO_RESOLUTION,
  DISPLAY_FINE_CROP_MODE_INTERNAL_RESOLUTION,
  DISPLAY_FINE_CROP_MODE_WINDOW_RESOLUTION,
  DISPLAY_FINE_CROP_MODE_MAX_COUNT,
} display_fine_crop_mode_t;

typedef enum : u8 {
  DISPLAY_ALIGNMENT_LEFT_OR_TOP,
  DISPLAY_ALIGNMENT_CENTER,
  DISPLAY_ALIGNMENT_RIGHT_OR_BOTTOM,
  DISPLAY_ALIGNMENT_COUNT,
} display_alignment_t;

typedef enum : u8 {
  DISPLAY_ROTATION_NORMAL,
  DISPLAY_ROTATION_ROTATE_90,
  DISPLAY_ROTATION_ROTATE_180,
  DISPLAY_ROTATION_ROTATE_270,
  DISPLAY_ROTATION_COUNT,
} display_rotation_t;

typedef enum : u8 {
  DISPLAY_SCALING_MODE_NEAREST,
  DISPLAY_SCALING_MODE_NEAREST_INTEGER,
  DISPLAY_SCALING_MODE_BILINEAR_SMOOTH,
  DISPLAY_SCALING_MODE_BILINEAR_HYBRID,
  DISPLAY_SCALING_MODE_BILINEAR_SHARP,
  DISPLAY_SCALING_MODE_BILINEAR_INTEGER,
  DISPLAY_SCALING_MODE_LANCZOS,
  DISPLAY_SCALING_MODE_COUNT,
} display_scaling_mode_t;

typedef enum : u8 {
  DISPLAY_EXCLUSIVE_FULLSCREEN_CONTROL_AUTOMATIC,
  DISPLAY_EXCLUSIVE_FULLSCREEN_CONTROL_DISALLOWED,
  DISPLAY_EXCLUSIVE_FULLSCREEN_CONTROL_ALLOWED,
  DISPLAY_EXCLUSIVE_FULLSCREEN_CONTROL_COUNT,
} display_exclusive_fullscreen_control_t;

typedef enum : u8 {
  DISPLAY_SCREENSHOT_MODE_SCREEN_RESOLUTION,
  DISPLAY_SCREENSHOT_MODE_INTERNAL_RESOLUTION,
  DISPLAY_SCREENSHOT_MODE_UNCORRECTED_INTERNAL_RESOLUTION,
  DISPLAY_SCREENSHOT_MODE_COUNT,
} display_screenshot_mode_t;

typedef enum : u8 {
  DISPLAY_SCREENSHOT_FORMAT_PNG,
  DISPLAY_SCREENSHOT_FORMAT_JPEG,
  DISPLAY_SCREENSHOT_FORMAT_WEBP,
  DISPLAY_SCREENSHOT_FORMAT_COUNT,
} display_screenshot_format_t;

typedef enum : u8 {
  PRESENT_SKIP_MODE_DISABLED,
  PRESENT_SKIP_MODE_WHEN_VSYNC_BLOCKS,
  PRESENT_SKIP_MODE_ALWAYS,
} present_skip_mode_t;

typedef enum : u8 {
  NOTIFICATION_LOCATION_TOP_LEFT,
  NOTIFICATION_LOCATION_TOP_CENTER,
  NOTIFICATION_LOCATION_TOP_RIGHT,
  NOTIFICATION_LOCATION_BOTTOM_LEFT,
  NOTIFICATION_LOCATION_BOTTOM_CENTER,
  NOTIFICATION_LOCATION_BOTTOM_RIGHT,
  NOTIFICATION_LOCATION_MAX_COUNT,
} notification_location_t;

typedef enum : u8 {
  ACHIEVEMENT_CHALLENGE_INDICATOR_MODE_DISABLED,
  ACHIEVEMENT_CHALLENGE_INDICATOR_MODE_PERSISTENT_ICON,
  ACHIEVEMENT_CHALLENGE_INDICATOR_MODE_TEMPORARY_ICON,
  ACHIEVEMENT_CHALLENGE_INDICATOR_MODE_NOTIFICATION,
  ACHIEVEMENT_CHALLENGE_INDICATOR_MODE_MAX_COUNT,
} achievement_challenge_indicator_mode_t;

typedef enum : u8 {
  CONTROLLER_TYPE_NONE,
  CONTROLLER_TYPE_DIGITAL_CONTROLLER,
  CONTROLLER_TYPE_ANALOG_CONTROLLER,
  CONTROLLER_TYPE_ANALOG_JOYSTICK,
  CONTROLLER_TYPE_GUNCON,
  CONTROLLER_TYPE_PLAYSTATION_MOUSE,
  CONTROLLER_TYPE_NEGCON,
  CONTROLLER_TYPE_NEGCON_RUMBLE,
  CONTROLLER_TYPE_JUSTIFIER,
  CONTROLLER_TYPE_POPN_CONTROLLER,
  CONTROLLER_TYPE_DDGO_CONTROLLER,
  CONTROLLER_TYPE_JOGCON,
  CONTROLLER_TYPE_COUNT,
} controller_type_t;

typedef enum : u8 {
  MEMORY_CARD_TYPE_NONE,
  MEMORY_CARD_TYPE_SHARED,
  MEMORY_CARD_TYPE_PER_GAME,
  MEMORY_CARD_TYPE_PER_GAME_TITLE,
  MEMORY_CARD_TYPE_PER_GAME_FILE_TITLE,
  MEMORY_CARD_TYPE_NON_PERSISTENT,
  MEMORY_CARD_TYPE_COUNT,
} memory_card_type_t;

typedef enum : u8 {
  MULTITAP_MODE_DISABLED,
  MULTITAP_MODE_PORT1_ONLY,
  MULTITAP_MODE_PORT2_ONLY,
  MULTITAP_MODE_BOTH_PORTS,
  MULTITAP_MODE_COUNT,
} multitap_mode_t;

enum {
  NUM_CONTROLLER_AND_CARD_PORTS = 8,
  NUM_MULTITAPS = 2,
  NUM_CONTROLLER_AND_CARD_PORTS_PER_MULTITAP = NUM_CONTROLLER_AND_CARD_PORTS / NUM_MULTITAPS,
};

typedef enum : u8 {
  CPU_FASTMEM_MODE_DISABLED,
  CPU_FASTMEM_MODE_MMAP,
  CPU_FASTMEM_MODE_LUT,
  CPU_FASTMEM_MODE_COUNT,
} cpu_fastmem_mode_t;

typedef enum : u8 {
  CDROM_MECHACON_VERSION_VC0A,
  CDROM_MECHACON_VERSION_VC0B,
  CDROM_MECHACON_VERSION_VC1A,
  CDROM_MECHACON_VERSION_VC1B,
  CDROM_MECHACON_VERSION_VD1,
  CDROM_MECHACON_VERSION_VC2,
  CDROM_MECHACON_VERSION_VC1,
  CDROM_MECHACON_VERSION_VC2J,
  CDROM_MECHACON_VERSION_VC2A,
  CDROM_MECHACON_VERSION_VC2B,
  CDROM_MECHACON_VERSION_VC3A,
  CDROM_MECHACON_VERSION_VC3B,
  CDROM_MECHACON_VERSION_VC3C,
  CDROM_MECHACON_VERSION_COUNT,
} cdrom_mechacon_version_t;

typedef enum : u8 {
  SAVE_STATE_COMPRESSION_MODE_UNCOMPRESSED,
  SAVE_STATE_COMPRESSION_MODE_DEFLATE_LOW,
  SAVE_STATE_COMPRESSION_MODE_DEFLATE_DEFAULT,
  SAVE_STATE_COMPRESSION_MODE_DEFLATE_HIGH,
  SAVE_STATE_COMPRESSION_MODE_ZST_LOW,
  SAVE_STATE_COMPRESSION_MODE_ZST_DEFAULT,
  SAVE_STATE_COMPRESSION_MODE_ZST_HIGH,
  SAVE_STATE_COMPRESSION_MODE_XZ_LOW,
  SAVE_STATE_COMPRESSION_MODE_XZ_DEFAULT,
  SAVE_STATE_COMPRESSION_MODE_XZ_HIGH,
  SAVE_STATE_COMPRESSION_MODE_COUNT,
} save_state_compression_mode_t;

typedef enum : u8 {
  FORCE_VIDEO_TIMING_MODE_DISABLED,
  FORCE_VIDEO_TIMING_MODE_NTSC,
  FORCE_VIDEO_TIMING_MODE_PAL,
  FORCE_VIDEO_TIMING_MODE_COUNT,
} force_video_timing_mode_t;

typedef enum : u8 {
  PIO_DEVICE_TYPE_NONE,
  PIO_DEVICE_TYPE_XPLORER_CART,
  PIO_DEVICE_TYPE_MAX_COUNT,
} pio_device_type_t;

/* Display aspect ratio: encodes Auto/Stretch/PAR1:1 sentinels via 0/-1 fields. */
typedef struct {
  s16 numerator;
  s16 denominator;
} display_aspect_ratio_t;

ALWAYS_INLINE display_aspect_ratio_t display_aspect_ratio_auto(void)
{
  display_aspect_ratio_t r = {0, 0};
  return r;
}
ALWAYS_INLINE display_aspect_ratio_t display_aspect_ratio_stretch(void)
{
  display_aspect_ratio_t r = {-1, -1};
  return r;
}
ALWAYS_INLINE display_aspect_ratio_t display_aspect_ratio_par1_1(void)
{
  display_aspect_ratio_t r = {-1, 0};
  return r;
}
ALWAYS_INLINE bool display_aspect_ratio_equals(const display_aspect_ratio_t* a, const display_aspect_ratio_t* b)
{
  return memcmp(a, b, sizeof(display_aspect_ratio_t)) == 0;
}
ALWAYS_INLINE bool display_aspect_ratio_is_valid(const display_aspect_ratio_t* a)
{
  return a->numerator > 0 && a->denominator > 0;
}

#endif /* CUPID_CORE_TYPES_H */
